[package]
name = "binary_tree"
version = "0.1.0"
authors = ["Hunter Lester <hlester@stubhub.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
